#!/bin/sh
#
# @name Boat
#

. ${R}etc/init.d/rc.boat_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=boat}

param set-default FD_ACT_EN 0
param set-default FD_ESCS_EN 0
param set-default CA_AIRFRAME 1
param set-default CP_DIST -1

param set-default SIM_GZ_HOME_LAT 47.687762
param set-default SIM_GZ_HOME_LON -122.404545

param set-default SENS_BOARD_ROT 4

param set-default CA_ROTOR_COUNT 2

param set-default CA_SV_CS_COUNT 2

param set-default CA_SV_CS0_TRQ_Y 0.5
param set-default CA_SV_CS0_TYPE 12

param set-default CA_SV_CS1_TRQ_Y 0.5
param set-default CA_SV_CS1_TYPE 12

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102

param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MAX2 1000
